### ISSUE TITLE
Support for paramiko > 4.0.0

### ISSUE THREAD

**Issue by sikmir** [huashengdun/webssh#412]
```sh
python3.13-webssh>     def get_specific_pkey(self, name, offset, password):
python3.13-webssh>         self.iostr.seek(offset)
python3.13-webssh>         logging.debug('Reset offset to {}.'.format(offset))
python3.13-webssh>
python3.13-webssh>         logging.debug('Try parsing it as {} type key'.format(name))
python3.13-webssh> >       pkeycls = getattr(paramiko, name+'Key')
python3.13-webssh>                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
python3.13-webssh> E       AttributeError: module 'paramiko' has no attribute 'DSSKey'. Did you mean: 'RSAKey'?
python3.13-webssh>
python3.13-webssh> webssh/handler.py:146: AttributeError
...
python3.13-webssh> ================== 4 failed, 88 passed, 26 warnings in 15.00s ==================
```
Removed support for the DSA (aka DSS) key algorithm, see https://www.paramiko.org/changelog.html

**Comment by kuja53** [comment]
That should be pretty easy fix. Just remove this line: https://github.com/huashengdun/webssh/blob/aaac2afe2a0d0c2fb8a8fd0813462d354682888a/webssh/handler.py#L109

But anyway I test current build with paramiko 4.0.0 and no issues on Mac with Python 3.13.
